packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^24.3.0
  '@typescript/native-preview': 7.0.0-dev.20260426.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  vitest: ^4.1.4
  zod: ^4.3.6

